In [42]:
import pandas as pd
import numpy as np
import scipy
from scipy import stats

Sales of products in four different regions is tabulated for males and females. 
Find if male-female buyer rations are similar across regions.

Defining test, as stated in problem statement,
H0: all proportions are equal
Ha: not all proportions are equal
    
As, from dataset we have to find the relationship between categorical variables, chi-squared test will be performed.


In [43]:
data_buyer = pd.read_csv('BuyerRatio.csv')
data_buyer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Observed Values  2 non-null      object
 1   East             2 non-null      int64 
 2   West             2 non-null      int64 
 3   North            2 non-null      int64 
 4   South            2 non-null      int64 
dtypes: int64(4), object(1)
memory usage: 208.0+ bytes


In [44]:
Observed_Values = data_buyer.iloc[:, 1:].values
Observed_Values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [45]:
val = stats.chi2_contingency(data_buyer.iloc[:,1:].values)#(dataset_table.values)
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [46]:
Expected_Values = val[3]
Expected_Values

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [57]:
chi_square = sum([(o-e)**2./e for o,e in zip(Observed_Values, Expected_Values)])
chi_square_statistic = chi_square[0]+chi_square[1]

print("chi-square statistic: ", chi_square_statistic)

chi-square statistic:  1.5152956451130446


In [58]:
no_of_rows = len(dataset_table.iloc[:,0])
no_of_columns = len(dataset_table.iloc[0,:])
ddof = (no_of_rows-1)*(no_of_columns-1)

alpha = 0.05

critical_value = chi2.ppf(q=1-alpha, df=ddof)

In [59]:
#p-value
p_value = 1-chi2.cdf(x=chi_square_statistic, df=ddof)

print("chi-square :        ", chi_square_statistic)
print('Critical value:     ', critical_value)
print('p-value:            ', p_value)
print('Significance level: ', alpha)
print('Degree of Freedom:  ', ddof)

chi-square :         1.5152956451130446
Critical value:      7.814727903251179
p-value:             0.6787446296467897
Significance level:  0.05
Degree of Freedom:   3



chi_square_statistic < critical_value (1.515<7.814):
    Retain H0, There is no relationship between 2 categorical variables,
    all proportions are equal
    
p_value > alpha (0.678>0.05):
    Retain H0, There is no relationship between 2 categorical variables.
    